steps:
  # Langkah 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$_GIT_COMMIT', '-f', 'frontend/Dockerfile', 'frontend/.']
    id: 'build-image'

  # Langkah 2: Push image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$_GIT_COMMIT']
    id: 'push-image'

  # Langkah 3: Deploy ke Cloud Run (Opsional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - '$TRIGGER_NAME'
      - '--image=gcr.io/$PROJECT_ID/$TRIGGER_NAME:$_GIT_COMMIT'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
    id: 'deploy-to-cloud-run'

options:
  logging: CLOUD_LOGGING_ONLY