steps:
  # Install dependencies using Node.js container
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd backend
        npm install --production
        
        
  # Deploy to App Engine using Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        gcloud app deploy app.yaml --project=$PROJECT_ID --quiet

options:
  logging: CLOUD_LOGGING_ONLY
  